### ISSUE TITLE
When go to profile image not render get error Failed to load resource: the server responded with a status of 404 

### ISSUE THREAD

**Issue by touchtool** [ThaiRepose/thairepose#114]
![image](https://user-images.githubusercontent.com/78125325/143731318-9d9e44fc-7a73-4670-af03-799c673c521b.png)
after refresh
![image](https://user-images.githubusercontent.com/78125325/143731325-c1672c00-61d5-4999-a0a4-bbe4d7fd0fc5.png)

**Comment by vitvara** [comment]
In your case, I didn't get the error.
I wonder what's happened 😢.
Can I contact you in discord?

**Comment by vitvara** [comment]
Sorry, we forgot to reset your profile so it get an error our bad.
My apologies.
