### ISSUE TITLE
[BUG] Rich Text | text colored cannot display in all trip page and can't click edit button

### ISSUE THREAD

**Issue by vitvara** [ThaiRepose/thairepose#61]
<img width="401" alt="image" src="https://user-images.githubusercontent.com/69972884/142726245-e92d4db9-89e3-49ca-9153-3caa7a97f2f0.png">
<img width="173" alt="image" src="https://user-images.githubusercontent.com/69972884/142726251-6affd65d-9bfd-4b7a-922f-d48c158db3b4.png">

**Comment by TaninDean** [comment]
Hard to Fix because you need to edit richtext
