### ISSUE TITLE
Link problems

### ISSUE THREAD

**Issue by ChanunyaO** [ThaiRepose/thairepose#76]
Three of these do not link to any page. It should link to some page, right?
<img width="295" alt="Screen Shot 2564-11-22 at 11 25 29" src="https://user-images.githubusercontent.com/78072892/142801014-190b2cd9-bdf8-4b95-abd2-a0afda5f9bd2.png">

**Comment by vitvara** [comment]
Thank you for your questions, I apologise for the delay in replying.
The deployed site doesn't have a page that you mentioned, now we finish all of that page it will be available by Friday.

**Comment by tboonma** [comment]
I've implemented in PR above. Please wait for deployment site. Thank to y'all 👍
