### ISSUE TITLE
[BUG]: Trip Blog Post can be create without a name

### ISSUE THREAD

**Issue by sirateek** [ThaiRepose/thairepose#93]
## Describe the bug

I can create the Trip Blog post without specifying any information. (Leave it null)

## Steps to reproduce the bug.
1. Go to the trip plan page and click the `Add Post` button.
2. On the create post page, Click the `Post` button without specifying any information.
3. The system creates the post for me without any alert.

## Expected behavior

The user shouldn't be able to create the trip plan without a name. It should be verified either on frontend or on backend by verifying the user input before saving the data into the database

## Screenshots

![Screen Shot 2564-11-25 at 01 19 02](https://user-images.githubusercontent.com/25188615/143293481-f41a21a3-7fb0-4a93-bf5c-0dcccde17822.png)

**Comment by TaninDean** [comment]
**Thank You For reporting**!!!
I will fix is fast as soon as possible I appreciate for your reporting.
